### PR TITLE
Docketeer 3.0 - Narwhals. Pre-launch PR

### PR DESCRIPTION
**Pull request by lo-guevara**
**New Features**
1. Added support for multiple user accounts

  - Upon first start up, Docketeer will automatically create a sysadmin account which users can log in to and use to provision access to other developers in their organization
  - Added login landing page so that users must submit a login form to authenticate themselves before accessing main Docketeer dashboard
  - Added forms to the settings tab which allow the user to update their email, phone number or password

2. Incorporated role-based privileges for enhanced security
Added support for three types of accounts: users, admins, and a sysadmin
  - Users: have access to core Docketeer features such as viewing container metrics, receiving notifications notification system, and updating account information
  - Admins: have access to the same features as User accounts. Admins also have more features available to them such as the ability to run containers from images, stop running containers, exit stopped containers, etc.
  - Sysadmin: have access to the same features as Admin accounts, but have an additional tab called ‘Users’ which they can use to view a complete user list for their organization and provision/revoke ‘Admin’ access. Additionally, the sysadmin has the ability to provision access to new users in the organization

3. Added improvements to notification system for increased reliability as well as support for email notification

  - Made some adjustments to the notification system callback chain to fix a bug where containers with threshold breaches were staged for notification but not communicated to the user
  - Added email support so that users can now configure which communication method they prefer to be contacted by
  - Incorporated an event emitter to the tail end of the notification system via the ipcRenderer and ipcMain modules for increased notification reliability

4. Support for configurable thresholds

  - With the addition of user accounts, we have altered the notification system to allow for configurable thresholds for certain metrics such as CPU usage, memory usage, and stopped containers.
  - Users can also configure whether they want to be contacted by email/phone
  - Threshold configurations are stored in the cloud database and saved in state upon login

5. Implemented cloud database support

  - Docketeer 3.0 marks the application’s transition from a standalone app that only monitors containers on the local machine to a cloud-based solution that offers remote monitoring for DevOps engineers
  - As part of this transition we have implemented support for a cloud-hosted relational database (PostgreSQL) to host an organization’s user data
  - Additionally, we aim in future iterations to also migrate container metrics from the containerized bind-mount so that users can remotely monitor the organization’s containers 
  - We have automated the creation of tables upon startup so that users only need to add a database connection URI to get their database up and running

6. Implemented a Dedicated backend server to efficiently route client requests, automate email notifications, and process database operations

  - By leveraging the Express.js framework we have streamlined future backend development
  - Added routers to efficiently route client requests and add modularity to a growing codebase
  - Added several routers to organize middleware functions by process

7. Additional Redux Functionality
  - Implemented additional reducers (userReducer, sessionReducer) to support multiple users and our role-based privileges feature

8. Modularized the code base
  - We have added some modularity to the existing codebase, particularly in the React components, though this is an ongoing process

**Next steps:**

1. Continue to clean up code base by removing unnecessary console logs
2. Add more comments to support future development
3. Incorporate OAuth

Co-authored-by: Griffin Silver 74221399+griffinrogersilver@users.noreply.github.com
Co-authored-by: Alex Smith 74221399+ajsmith925@users.noreply.github.com
Co-authored-by: Charles Ryu 78817594+charcharryu@users.noreply.github.com
Co-authored-by: Catherine Larcheveque 79517320+clarcheveque@users.noreply.github.com

### CODE REVIEW

**Comment by griffinrogersilver** [comment]
Thank you Lorenzo. Very thorough

**Review by griffinrogersilver — APPROVED** [review]
Nicely done!

**Review by charcharryu — APPROVED** [review]
Looking good, thanks for the PR write up.

**Review by ajsmith925 — APPROVED** [review]
nice and neat, one step closer to launch!

**Review by clarcheveque — APPROVED** [review]
Launch is right around the corner. Let's finish strong, team!

**Pull request merged**
